services:
  - type: web
    name: ekart-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
